export const PIPELINE_STAGES = ["Screening", "Interview", "Shortlisted", "Offer", "Hired"];

export const AVATAR_COLORS = {
  AR: "bg-blue-100 text-blue-700",
  MT: "bg-purple-100 text-purple-700",
  JK: "bg-green-100 text-green-700",
  SP: "bg-orange-100 text-orange-700",
  CW: "bg-pink-100 text-pink-700",
  RC: "bg-indigo-100 text-indigo-700",
  ML: "bg-teal-100 text-teal-700",
  TB: "bg-red-100 text-red-700",
  AM: "bg-yellow-100 text-yellow-700",
  QF: "bg-cyan-100 text-cyan-700",
  SC: "bg-violet-100 text-violet-700",
  MJ: "bg-lime-100 text-lime-700",
  EV: "bg-rose-100 text-rose-700",
  JP: "bg-sky-100 text-sky-700",
};

export const DYNAMIC_AVATAR_COLORS = [
  "bg-blue-100 text-blue-700",
  "bg-purple-100 text-purple-700",
  "bg-green-100 text-green-700",
  "bg-orange-100 text-orange-700",
  "bg-pink-100 text-pink-700",
  "bg-indigo-100 text-indigo-700",
  "bg-teal-100 text-teal-700",
  "bg-rose-100 text-rose-700",
  "bg-cyan-100 text-cyan-700",
  "bg-amber-100 text-amber-700",
  "bg-emerald-100 text-emerald-700",
  "bg-sky-100 text-sky-700",
];

export const getAvatarColor = () => {
  return "bg-[#EEF2FB] text-[#1B4DA0] border border-[#1B4DA0]/20 shadow-sm";
};

export const mockCandidates = [
  {
    id: "c1",
    name: "Alex Rivera",
    role: "Senior Frontend Engineer",
    stage: "Screening",
    avatar: "AR",
    email: "alex.r@example.com",
    phone: "+1 (555) 234-5678",
    appliedDate: "2024-11-14",
    jobId: "j1",
    skills: ["React", "TypeScript", "CSS", "Performance"],
    stageHistory: [{ stage: "Screening", date: "2024-11-14" }],
    lastMovedDate: "2024-11-14",
  },
  {
    id: "c2",
    name: "Maya Thompson",
    role: "Product Manager",
    stage: "Applied",
    avatar: "MT",
    email: "maya.t@example.com",
    phone: "+1 (555) 345-6789",
    appliedDate: "2024-11-13",
    jobId: "j2",
    skills: ["Product strategy", "Roadmapping", "Agile", "Analytics"],
    stageHistory: [{ stage: "Applied", date: "2024-11-13" }],
    lastMovedDate: "2024-11-01",
  },
  {
    id: "c3",
    name: "Jordan Kim",
    role: "UX/UI Designer",
    stage: "Screening",
    avatar: "JK",
    email: "jordan.k@example.com",
    phone: "+1 (555) 456-7890",
    appliedDate: "2024-11-10",
    jobId: "j3",
    skills: ["Figma", "User research", "Design systems", "Prototyping"],
    stageHistory: [
      { stage: "Applied", date: "2024-11-10" },
      { stage: "Screening", date: "2024-11-13" },
    ],
    lastMovedDate: "2024-11-13",
  },
  {
    id: "c4",
    name: "Sam Patel",
    role: "Backend Engineer",
    stage: "Screening",
    avatar: "SP",
    email: "sam.p@example.com",
    phone: "+1 (555) 567-8901",
    appliedDate: "2024-11-11",
    jobId: "j6",
    skills: ["Node.js", "PostgreSQL", "Docker", "AWS"],
    stageHistory: [
      { stage: "Applied", date: "2024-11-11" },
      { stage: "Screening", date: "2024-11-14" },
    ],
  },
  {
    id: "c5",
    name: "Casey Wu",
    role: "Senior Frontend Engineer",
    stage: "Interview",
    avatar: "CW",
    email: "casey.w@example.com",
    phone: "+1 (555) 678-9012",
    appliedDate: "2024-11-05",
    jobId: "j1",
    skills: ["React", "TypeScript", "GraphQL", "Testing"],
    stageHistory: [
      { stage: "Applied", date: "2024-11-05" },
      { stage: "Screening", date: "2024-11-08" },
      { stage: "Interview", date: "2024-11-12" },
    ],
  },
  {
    id: "c6",
    name: "Riley Chen",
    role: "Product Manager",
    stage: "Interview",
    avatar: "RC",
    email: "riley.c@example.com",
    phone: "+1 (555) 789-0123",
    appliedDate: "2024-11-06",
    jobId: "j2",
    skills: ["B2B SaaS", "Data analysis", "Stakeholder mgmt", "Roadmapping"],
    stageHistory: [
      { stage: "Applied", date: "2024-11-06" },
      { stage: "Screening", date: "2024-11-10" },
      { stage: "Interview", date: "2024-11-13" },
    ],
  },
  {
    id: "c7",
    name: "Morgan Lee",
    role: "UX/UI Designer",
    stage: "Offer",
    avatar: "ML",
    email: "morgan.l@example.com",
    phone: "+1 (555) 890-1234",
    appliedDate: "2024-10-28",
    jobId: "j3",
    skills: ["Figma", "Motion design", "UX research", "Component design"],
    stageHistory: [
      { stage: "Applied", date: "2024-10-28" },
      { stage: "Screening", date: "2024-11-01" },
      { stage: "Interview", date: "2024-11-05" },
      { stage: "Offer", date: "2024-11-12" },
    ],
  },
  {
    id: "c8",
    name: "Taylor Brooks",
    role: "Backend Engineer",
    stage: "Hired",
    avatar: "TB",
    email: "taylor.b@example.com",
    phone: "+1 (555) 901-2345",
    appliedDate: "2024-10-15",
    jobId: "j6",
    skills: ["Go", "Kubernetes", "PostgreSQL", "Redis"],
    stageHistory: [
      { stage: "Applied", date: "2024-10-15" },
      { stage: "Screening", date: "2024-10-19" },
      { stage: "Interview", date: "2024-10-24" },
      { stage: "Offer", date: "2024-11-01" },
      { stage: "Hired", date: "2024-11-08" },
    ],
  },
  {
    id: "c9",
    name: "Avery Martinez",
    role: "Sales Development Rep",
    stage: "Screening",
    avatar: "AM",
    email: "avery.m@example.com",
    phone: "+1 (555) 012-3456",
    appliedDate: "2024-11-15",
    jobId: "j7",
    skills: ["Cold outreach", "CRM", "Lead gen", "Communication"],
    stageHistory: [{ stage: "Screening", date: "2024-11-15" }],
  },
  {
    id: "c10",
    name: "Quinn Foster",
    role: "Senior Frontend Engineer",
    stage: "Screening",
    avatar: "QF",
    email: "quinn.f@example.com",
    phone: "+1 (555) 123-4567",
    appliedDate: "2024-11-09",
    jobId: "j1",
    skills: ["React", "Vue", "CSS animations", "Accessibility"],
    stageHistory: [
      { stage: "Applied", date: "2024-11-09" },
      { stage: "Screening", date: "2024-11-13" },
    ],
  },
];

export const mockInterviews = [
  {
    id: "i1",
    candidateId: "c5",
    candidateName: "Casey Wu",
    candidateAvatar: "CW",
    role: "Senior Frontend Engineer",
    interviewer: "Sarah Chen",
    interviewerAvatar: "SC",
    date: "2024-11-18",
    time: "10:00",
    duration: 60,
    type: "Video",
    meetingLink: "https://meet.google.com/abc-defg-hij",
    notes: "Technical deep-dive, focus on system design",
    status: "Completed",
    feedbackStatus: "Submitted",
    prepLevel: "High",
  },
  {
    id: "i2",
    candidateId: "c6",
    candidateName: "Riley Chen",
    candidateAvatar: "RC",
    role: "Product Manager",
    interviewer: "Marcus Johnson",
    interviewerAvatar: "MJ",
    date: "2024-11-18",
    time: "14:00",
    duration: 45,
    type: "Video",
    meetingLink: "https://zoom.us/j/123456789",
    notes: "Product case study presentation",
    status: "In-Progress",
    feedbackStatus: "Pending",
    prepLevel: "Medium",
  },
  {
    id: "i3",
    candidateId: "c7",
    candidateName: "Morgan Lee",
    candidateAvatar: "ML",
    role: "UX/UI Designer",
    interviewer: "Elena Vasquez",
    interviewerAvatar: "EV",
    date: "2024-11-19",
    time: "11:00",
    duration: 60,
    type: "In-Person",
    notes: "Portfolio review and culture fit",
    status: "Scheduled",
    feedbackStatus: "Pending",
    prepLevel: "High",
  },
  {
    id: "i4",
    candidateId: "c3",
    candidateName: "Jordan Kim",
    candidateAvatar: "JK",
    role: "UX/UI Designer",
    interviewer: "Elena Vasquez",
    interviewerAvatar: "EV",
    date: "2024-11-19",
    time: "15:30",
    duration: 30,
    type: "Video",
    meetingLink: "https://meet.google.com/xyz-uvwx-yz",
    notes: "Initial screening call",
    status: "Scheduled",
    feedbackStatus: "Pending",
    prepLevel: "Low",
  },
  {
    id: "i5",
    candidateId: "c4",
    candidateName: "Sam Patel",
    candidateAvatar: "SP",
    role: "Backend Engineer",
    interviewer: "Sarah Chen",
    interviewerAvatar: "SC",
    date: "2024-11-20",
    time: "09:30",
    duration: 60,
    type: "Video",
    notes: "Technical assessment - coding challenge review",
    status: "Scheduled",
    feedbackStatus: "Pending",
    prepLevel: "Medium",
  },
  {
    id: "i6",
    candidateId: "c10",
    candidateName: "Quinn Foster",
    candidateAvatar: "QF",
    role: "Senior Frontend Engineer",
    interviewer: "James Park",
    interviewerAvatar: "JP",
    date: "2024-11-20",
    time: "13:00",
    duration: 45,
    type: "In-Person",
    notes: "Culture fit and team introduction",
    status: "Scheduled",
    feedbackStatus: "Pending",
    prepLevel: "High",
  },
];

export const INTERVIEW_DATES = ["2024-11-18", "2024-11-19", "2024-11-20"];

export const DATE_LABELS = {
  "2024-11-18": "Today — Monday, Nov 18",
  "2024-11-19": "Tomorrow — Tuesday, Nov 19",
  "2024-11-20": "Wednesday, Nov 20",
};
